# AV1
type: video
id: 20000 # AV01 (0002_0000)
idstr: av01
enabled: true
use: ffmpeg
ext: ".mp4"
mime: "video/mp4; codecs=av01.0.[level:%m(mapLevel)]M.[depth:%02d]"
audios: [mp4a, opus]

options:
  threads: 2
  resizeMethod: spline16
  codec: libsvtav1
  pixelFormat: yuv420p
  preset: 4
  svtav1-params: "bias-pct=1"

tune:
  bpp: 0.055
  increase: 0.8
  decrease: 0.8

variants:
- id: 20180 # AV01 (0002_0000) + 180p (0000_0180)
  idstr: av01_180p
  bitrate: 200k
  constraints:
    height: ">180"
  options:
    maxSize: 432x180
    maxFramerate: 30
    postFilters:
    - pp=hb|8|39/vb|8|39/dr/fq|12
    - hqdn3d
    - unsharp=5:5:0.5:3:3:0.5

- id: 20360 # AV01 (0002_0000) + 360p (0000_0360)
  idstr: av01_360p
  bitrate: 520k # 180pbr x2.6
  constraints:
    height: ">360"
  options:
    maxSize: 864x360
    maxFramerate: 30
    postFilters:
    - pp=hb|8|39/vb|8|39/dr/fq|8
    - hqdn3d
    - unsharp=5:5:0.25:3:3:0.25

- id: 20720 # AV01 (0002_0000) + 720p (0000_0720)
  idstr: av01_720p
  bitrate: 1456k # 360pbr x2.8
  constraints:
    height: ">720"
  options:
    maxSize: 1728x720
    maxFramerate: 30

- id: 29999 # AV01 (0002_0000) + (native)p (0000_9999)
  idstr: av01_ntvp
  # DO NOT USE "bitrate" ATTRIBUTE!!
  options:
    maxFramerate: 120
