# MPEG-4 Part 10 Advanced Video Coding
type: video
id: 10000 # AVC1 (0001_0000)
idstr: avc1
enabled: true
use: ffmpeg
ext: ".mp4"
mime: "video/mp4; codecs=avc1.6400[levelhex]"
# Baseline: video/mp4; codecs="avc1.4200[levelhex]"
# Main:     video/mp4; codecs="avc1.4d00[levelhex]"
# High 10:  video/mp4; codecs="avc1.6e00[levelhex]"
audios: mp4a
useHls: true

options:
  threads: 2
  codec: libx264
  pixelFormat: yuv420p
  profile: "high"
  preset: "slow"
  fpsmax: 30
  sc_threshold: 0

tune:
  bpp: 0.11
  increase: 0.8
  decrease: 0.8

variants:
- id: 10180 # AVC1 (0001_0000) + 180p (0000_0180)
  idstr: avc1_180p
  bitrate: 320k
  constraints:
    height: ">180"
  options:
    maxSize: 432x180
    maxFramerate: 30

- id: 10360 # AVC1 (0001_0000) + 360p (0000_0360)
  idstr: avc1_360p
  bitrate: 640k
  constraints:
    height: ">360"
  options:
    maxSize: 864x360
    maxFramerate: 30

- id: 10720 # AVC1 (0001_0000) + 720p (0000_0720)
  idstr: avc1_720p
  bitrate: 2M
  constraints:
    height: ">720"
  options:
    maxSize: 1728x720
    maxFramerate: 30

- id: 19999 # AVC1 (0001_0000) + (native)p (0000_9999)
  idstr: avc1_ntvp
  # DO NOT USE "bitrate" ATTRIBUTE!!
  options:
    maxFramerate: 120
