# AV1 Image File Format
type: image
id: 110000 # AVIF (0012_0000)
idstr: avif
enabled: true
public: true
use: ffmpeg
ext: ".avif"
mime: "image/avif"

options:
  codec: libaom-av1
  # recommended: 20-40
  # (--cq-level in aomenc)
  crf: 37
  resizeMethod: bicubic
  resizeMode: crop
  colorRange: tv
  transferCharacteristics: bt709
  matrixCoefficients: bt709

variants:
- id: 110110 # AVIF (0012_0000) + type 1 (0000_0100) + 1x (0000_0010)
  idstr: avif_225p_1x
  filename: "t@1.avif"
  options:
    maxSize: 400x225
    crf: 37

- id: 110120 # AVIF (0012_0000) + type 1 (0000_0100) + 2x (0000_0020)
  idstr: avif_225p_2x
  filename: "t@2.avif"
  constraints:
    height: ">=450"
  options:
    maxSize: 800x450
    crf: 46

- id: 110130 # AVIF (0012_0000) + type 1 (0000_0100) + 3x (0000_0030)
  idstr: avif_225p_3x
  filename: "t@3.avif"
  constraints:
    height: ">=675"
  options:
    maxSize: 1200x675
    crf: 52
