# ISO/IEC 23008-2 High Efficiency Video Coding
type: video
id: 50000 # HVC1 (0005_0000)
idstr: hvc1
enabled: false
use: ffmpeg
ext: ".mp4"
audios: mp4a

options:
  threads: 2
  resizeMethod: bicubic
  codec: libx265
  tag: hvc1 # Require Apple platforms
  pixelFormat: yuv420p
  profile: main
  preset: slow
  sc_threshold: 0

tune:
  bpp: 0.075
  increase: 0.75
  decrease: 0.75

variants:
- id: 50180 # HVC1 (0005_0000) + 180p (0000_0180)
  idstr: hvc1_180p
  bitrate: 256k
  constraints:
    height: ">180"
  options:
    maxSize: 432x180
    maxFramerate: 30

- id: 50360 # HVC1 (0005_0000) + 360p (0000_0360)
  idstr: hvc1_360p
  bitrate: 512k
  constraints:
    height: ">360"
  options:
    maxSize: 864x360
    maxFramerate: 30

- id: 50720 # HVC1 (0005_0000) + 720p (0000_0720)
  idstr: hvc1_720p
  bitrate: 1.6M
  constraints:
    height: ">720"
  options:
    maxSize: 1728x720
    maxFramerate: 30

- id: 59999 # HVC1 (0005_0000) + (native)p (0000_9999)
  idstr: hvc1_ntvp
  # DO NOT USE "bitrate" ATTRIBUTE!!
  options:
    maxFramerate: 120
