# Joint Photographic Experts Group
type: image
id: 100000 # JPEG (0010_0000)
idstr: jpeg
enabled: true
public: true
use: ffmpeg
ext: ".jpg"
mime: "image/jpeg"

options:
  quality: 8
  resize: crop

variants:
- id: 100110 # JPEG (0010_0000) + type 1 (0000_0100) + 1x (0000_0010)
  idstr: jpeg_225p_1x
  filename: "t@1.jpg"
  options:
    maxSize: 400x225
    quality: 8

- id: 100120 # JPEG (0010_0000) + type 1 (0000_0100) + 2x (0000_0020)
  idstr: jpeg_225p_2x
  filename: "t@2.jpg"
  options:
    maxSize: 800x450
    quality: 18
