# Opus
type: audio
id: 2000000 # Opus (0200_0000)
idstr: opus
enabled: true
use: ffmpeg
ext: ".webm"
mime: "audio/webm; codecs=opus"

options:
  codec: libopus
  channel: 2

variants:
- id: 2000048 # Opus (0200_0000) + 48 kbps (0000_0048)
  idstr: opus_48k
  bitrate: 46k
  options:
    sampleRate: [16000, 22050, 24000, 32000, 44100, 48000]

- id: 2000096 # Opus (0200_0000) + 96 kbps (0000_0096)
  idstr: opus_96k
  bitrate: 92k
  constraints:
    sampleRate: ">=32000"
  options:
    sampleRate: [32000, 44100, 48000]
