# Opus
id: 210000
idstr: opus
type: audio
enabled: true
use: ffmpeg
ext: ".webm"

encoder:
  codec: libopus
  channel: 2

variants:
- id: 210048
  idstr: opus_48k
  enabled: true
  bitrate: 46k
  encoder:
    sampleRate: [16000, 22050, 24000, 32000, 44100, 48000]

- id: 210096
  idstr: opus_96k
  enabled: true
  bitrate: 92k
  constraints:
    sampleRate: ">=32000"
  encoder:
    sampleRate: [32000, 44100, 48000]
