# WebP
type: image
id: 130000 # WebP (0013_0000)
idstr: webp
enabled: true
public: true
use: ffmpeg
ext: ".webp"
mime: "image/webp"

options:
  quality: 85
  resize: crop

variants:
- id: 130110 # WebP (0013_0000) + type 1 (0000_0100) + 1x (0000_0010)
  idstr: webp_225p_1x
  filename: "t@1.webp"
  options:
    maxSize: 400x225
    quality: 25

- id: 130120 # WebP (0013_0000) + type 1 (0000_0100) + 2x (0000_0020)
  idstr: webp_225p_2x
  filename: "t@2.webp"
  constraints:
    height: ">=450"
  options:
    maxSize: 800x450
    quality: 12
