# Server settings
# [Note] Quickly start with the command "npm run openssl:init"
http:
  http2: true
  host: localhost
  port: 443
  ssl:
    key: .dev/key.pem
    cert: .dev/cert.pem
  headers:
    Referrer-Policy: no-referrer
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Frame-Options: DENY

# Asset settings
assets:
  enableDeploy: true
  outputPath: .assets
  baseUri: /a

# Media settings
media:
  enableDeploy: true
  outputPath: .media
  baseUri: /m

# Redis settings
redis:
  host: localhost
  port: 6379
  username: default

# Session settings
# [Note] Quickly start with the command "npm run session:init"
session:
  cookieName: __Host-s # Require "cookieSecure: true". Rename it if you use http.
  cookieMaxAge: 14 days
  cookieSecure: true
  key: .dev/session.key
