# Server settings
# [Note] Quickly start with the command "npm run openssl:init"
http:
  http2: true
  host: localhost
  port: 443
  ssl:
    key: .dev/key.pem
    cert: .dev/cert.pem

# Asset settings
assets:
  enableDeploy: true
  outputPath: .assets
  baseUri: /a

# Media settings
media:
  enableDeploy: true
  outputPath: .media
  baseUri: /m

# Redis settings
redis:
  host: localhost
  port: 6379
  username: default

# Session settings
# [Note] Quickly start with the command "npm run session:init"
session:
  cookieName: __Host-s
  cookieMaxAge: 14 days
  key: .dev/session.key
