# Server settings
# [Note] Quickly start with the command "npm run openssl:init"
http:
  http2: true
  host: localhost
  port: 443
  ssl:
    key: .dev/key.pem
    cert: .dev/cert.pem

# Session settings
# [Note] Quickly start with the command "npm run session:init"
session:
  cookieName: __Host-s
  cookieMaxAge: 14 days
  key: .dev/session.key
