# Server settings
http:
  http2: false
  host: clogs
  port: 3000
  headers: { }

# Asset settings
assets:
  enableDeploy: false

# Media settings
media:
  enableDeploy: false

# Redis settings
redis:
  host: redis
  port: 6379
  username: default

# Session settings
session:
  cookieName: __Host-s
  cookieMaxAge: 30 mins
  cookieSecure: true
  key: .dev/session.key
